db:
  image: postgres
  ports:
    - "5432:5432" # Bind host port 5432 to PostgreSQL port 5432
  environment:
    LC_ALL: C.UTF-8

lib:
  build: .
  links:
    - db:postgres.local
  environment:
    TEST_DATABASE_URL:   "user=postgres dbname=ttest sslmode=disable host=postgres.local" #postgres://:@:5432/ttest
