db:
  image: postgres
  environment:
    LC_ALL: C.UTF-8

lib:
  build: .
  volumes:
    - .:/go/src/github.com/wawandco/transporter
  links:
    - db:postgres.local
  environment:
    TRANS_TESTING_FOLDER: "/go/src/testing"
    TEST_DATABASE_URL:   "user=postgres dbname=ttest sslmode=disable host=postgres.local" #postgres://:@:5432/ttest
